name = "tiinyapp-farm"
account_id = "5a845e69fbed4f4e64e2176d86637680"
compatibility_date = "2026-09-12"
workers_dev = false

[[routes]]
pattern = "tiinyapp.farm"
custom_domain = true

[assets]
directory = "./site/dist"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"
